### ISSUE TITLE
command `null` called

### ISSUE THREAD

**Issue by shiftypenguin** [siblynx/uinit_rc#1]
You call the command `null` a couple times in /etc/boot, but you haven't included the function/script. 

I eventually found it in your R2 repository, but maybe you could add a note here, or include it as a function or as a script?

**Comment by siblynx** [comment]
uinit_rc was forked as a dedicated repository just for tracking the development of boot scripts for R2. Hence any R2-isms can appear here. I mentioned this fact in README.md now.
